
var fs    = require('fs'),
    path  = require('path'),
    filename, filewoext, data, base_ptx, default_colorizer;

var filename = "ptx.h";
if (process.argv.length >= 3) {
  filename = path.resolve(process.argv[2], filename);
}

var files = ["base_ptx", "default_colorizer"];

var filewoext = path.basename(filename, path.extname(filename)).toLowerCase();
var data = "// Autogenerated by hdrgen.js\n\n#ifndef __" + filewoext + "_h\n#define __" + filewoext + "_h\n\n";

files.forEach(function(file, idx) {
  data += "const char " + file + "[] = \"\\n\\\n";
  var tmp = fs.readFileSync(file + ".ptx", "utf8");
  tmp = tmp.split("\n").join("\\n\\\n");
  data += tmp + "\";\n\n";
});

data += "#endif\n\n";

fs.writeFileSync(filename, data);

